baseURL = "https://blog.stat90.com/"
title = "Stat90 Blog"
theme = "PaperMod"
publishDir = "docs"

[params]
  label.text = "Stat90 blog"
  
  defaultTheme = "dark"  # Set dark mode as default
  disableThemeToggle = false

  [params.assets]
    favicon = "/favicon.ico"